import type { DatabaseService } from '../main/db/database'

export async function dispatchDatabaseCall(
  db: DatabaseService,
  method: string,
  args: unknown[]
): Promise<unknown> {
  switch (method) {
    case 'getSetting': return db.getSetting(args[0] as string)
    case 'setSetting': return db.setSetting(args[0] as string, args[1] as string)
    case 'deleteSetting': return db.deleteSetting(args[0] as string)
    case 'getAllSettings': return db.getAllSettings()
    case 'getAllProjects': return db.getAllProjects()
    case 'getProject': return db.getProject(args[0] as string)
    case 'getProjectByPath': return db.getProjectByPath(args[0] as string)
    case 'createProject': return db.createProject(args[0] as never)
    case 'updateProject': return db.updateProject(args[0] as string, args[1] as never)
    case 'deleteProject': return db.deleteProject(args[0] as string)
    case 'touchProject': return db.touchProject(args[0] as string)
    case 'reorderProjects': return db.reorderProjects(args[0] as string[])
    case 'getProjectIdsSortedByLastMessage': return db.getProjectIdsSortedByLastMessage()
    case 'getWorktree': return db.getWorktree(args[0] as string)
    case 'getWorktreeByPath': return db.getWorktreeByPath(args[0] as string)
    case 'getWorktreesByProject': return db.getWorktreesByProject(args[0] as string)
    case 'getActiveWorktreesByProject': return db.getActiveWorktreesByProject(args[0] as string)
    case 'getRecentlyActiveWorktrees': return db.getRecentlyActiveWorktrees(args[0] as number)
    case 'getPinnedWorktrees': return db.getPinnedWorktrees()
    case 'createWorktree': return db.createWorktree(args[0] as never)
    case 'updateWorktree': return db.updateWorktree(args[0] as string, args[1] as never)
    case 'deleteWorktree': return db.deleteWorktree(args[0] as string)
    case 'archiveWorktree': return db.archiveWorktree(args[0] as string)
    case 'touchWorktree': return db.touchWorktree(args[0] as string)
    case 'updateWorktreeContext': return db.updateWorktreeContext(args[0] as string, args[1] as string | null)
    case 'appendSessionTitle': return db.appendSessionTitle(args[0] as string, args[1] as string)
    case 'addAttachment': return db.addAttachment(args[0] as string, args[1] as never)
    case 'removeAttachment': return db.removeAttachment(args[0] as string, args[1] as string)
    case 'attachPR': return db.attachPR(args[0] as string, args[1] as number, args[2] as string)
    case 'detachPR': return db.detachPR(args[0] as string)
    case 'updateWorktreeModel': return db.updateWorktreeModel(
      args[0] as string,
      args[1] as string,
      args[2] as string,
      args[3] as string | null
    )
    case 'getWorktreeBySessionId': return db.getWorktreeBySessionId(args[0] as string)
    case 'createSession': return db.createSession(args[0] as never)
    case 'getSession': return db.getSession(args[0] as string)
    case 'getSessionsByWorktree': return db.getSessionsByWorktree(args[0] as string)
    case 'getSessionsByProject': return db.getSessionsByProject(args[0] as string)
    case 'getActiveSessionsByWorktree': return db.getActiveSessionsByWorktree(args[0] as string)
    case 'getSessionsByConnection': return db.getSessionsByConnection(args[0] as string)
    case 'getActiveSessionsByConnection': return db.getActiveSessionsByConnection(args[0] as string)
    case 'updateSession': return db.updateSession(args[0] as string, args[1] as never)
    case 'deleteSession': return db.deleteSession(args[0] as string)
    case 'searchSessions': return db.searchSessions(args[0] as never)
    case 'getSessionDraft': return db.getSessionDraft(args[0] as string)
    case 'updateSessionDraft': return db.updateSessionDraft(args[0] as string, args[1] as string | null)
    case 'getSessionMessages': return db.getSessionMessages(args[0] as string)
    case 'getSessionActivities': return db.getSessionActivities(args[0] as string)
    case 'listSpaces': return db.listSpaces()
    case 'createSpace': return db.createSpace(args[0] as never)
    case 'updateSpace': return db.updateSpace(args[0] as string, args[1] as never)
    case 'deleteSpace': return db.deleteSpace(args[0] as string)
    case 'reorderSpaces': return db.reorderSpaces(args[0] as string[])
    case 'assignProjectToSpace': return db.assignProjectToSpace(args[0] as string, args[1] as string)
    case 'removeProjectFromSpace': return db.removeProjectFromSpace(args[0] as string, args[1] as string)
    case 'getProjectIdsForSpace': return db.getProjectIdsForSpace(args[0] as string)
    case 'getAllProjectSpaceAssignments': return db.getAllProjectSpaceAssignments()
    case 'getDiffCommentsByWorktree': return db.getDiffCommentsByWorktree(args[0] as string)
    case 'createDiffComment': return db.createDiffComment(args[0] as never)
    case 'updateDiffComment': return db.updateDiffComment(args[0] as string, args[1] as never)
    case 'setDiffCommentOutdated': return db.setDiffCommentOutdated(args[0] as string, args[1] as boolean)
    case 'deleteDiffComment': return db.deleteDiffComment(args[0] as string)
    case 'clearAllDiffComments': return db.clearAllDiffComments(args[0] as string)
    case 'getAllConnections': return db.getAllConnections()
    case 'getConnection': return db.getConnection(args[0] as string)
    case 'createConnection': return db.createConnection(args[0] as never)
    case 'updateConnection': return db.updateConnection(args[0] as string, args[1] as never)
    case 'deleteConnection': return db.deleteConnection(args[0] as string)
    case 'createConnectionMember': return db.createConnectionMember(args[0] as never)
    case 'deleteConnectionMember': return db.deleteConnectionMember(args[0] as string, args[1] as string)
    case 'getConnectionMembersByWorktree': return db.getConnectionMembersByWorktree(args[0] as string)
    case 'getPinnedConnections': return db.getPinnedConnections()
    case 'getSchemaVersion': return db.getSchemaVersion()
    case 'tableExists': return db.tableExists(args[0] as string)
    case 'getIndexes': return db.getIndexes()
    default:
      throw new Error('db_method_not_allowed')
  }
}
